# Generated by Django 3.1.1 on 2020-09-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="channels/profile"
                    ),
                ),
                ("about", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
