# Generated by Django 3.1.1 on 2020-09-26 21:13

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0002_channel_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channel",
            options={"get_latest_by": "modified"},
        ),
        migrations.AddField(
            model_name="channel",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="channel",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
