# Generated by Django 3.1.1 on 2020-09-27 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("channels", "0003_auto_20200926_2113"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                related_name="channel_subscribed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
