# Generated by Django 3.1.1 on 2020-09-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0004_channel_subscribers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
