# Generated by Django 3.1.1 on 2020-09-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved",
            field=models.ManyToManyField(
                related_name="saved_by", to="multimedia.Media"
            ),
        ),
    ]
