# Generated by Django 3.1.1 on 2020-09-26 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Likes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("val", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("title", models.CharField(max_length=100)),
                ("Description", models.TextField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="multimedia/thumbnail"
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="channels.channel",
                    ),
                ),
                (
                    "comments",
                    models.ManyToManyField(
                        related_name="media", to="multimedia.Comments"
                    ),
                ),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True, related_name="media", to="multimedia.Likes"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="multimedia.media",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="multimedia/article"
                    ),
                ),
                ("content", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("multimedia.media",),
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="multimedia.media",
                    ),
                ),
                ("link", models.FileField(upload_to="multimedia/audios")),
            ],
            options={
                "abstract": False,
            },
            bases=("multimedia.media",),
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="multimedia.media",
                    ),
                ),
                ("link", models.FileField(blank=True, upload_to="multimedia/pictures")),
            ],
            options={
                "abstract": False,
            },
            bases=("multimedia.media",),
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "media_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="multimedia.media",
                    ),
                ),
                ("link", models.FileField(upload_to="multimedia/videos")),
            ],
            options={
                "abstract": False,
            },
            bases=("multimedia.media",),
        ),
    ]
