# Generated by Django 3.1.1 on 2020-09-25 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0001_initial"),
        ("multimedia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="channels.channel",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="media", to="multimedia.Likes"
            ),
        ),
    ]
