# Generated by Django 3.1.1 on 2020-09-26 21:13

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("multimedia", "0002_auto_20200926_0408"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="audio",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="comments",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="likes",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="media",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="picture",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="video",
            options={"get_latest_by": "modified"},
        ),
        migrations.RemoveField(
            model_name="comments",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="comments",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="likes",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="likes",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="media",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="media",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="comments",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comments",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="likes",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="likes",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="media",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
