# Generated by Django 3.1.1 on 2020-09-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("multimedia", "0003_auto_20200926_2113"),
    ]

    operations = [
        migrations.RenameField(
            model_name="media",
            old_name="Description",
            new_name="description",
        ),
    ]
