# Generated by Django 3.1.1 on 2020-09-27 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("multimedia", "0004_auto_20200926_2136"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("picture", "Picture"),
                    ("article", "Article"),
                ],
                default="video",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="media",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="views", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
