# Generated by Django 3.1.1 on 2020-09-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("multimedia", "0005_auto_20200927_1257"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="image",
            new_name="media_url",
        ),
        migrations.RenameField(
            model_name="audio",
            old_name="link",
            new_name="media_url",
        ),
        migrations.RenameField(
            model_name="picture",
            old_name="link",
            new_name="media_url",
        ),
        migrations.RenameField(
            model_name="video",
            old_name="link",
            new_name="media_url",
        ),
    ]
