# Generated by Django 3.1.1 on 2020-09-27 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("multimedia", "0007_auto_20200927_1452"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="message",
            field=models.TextField(default="blah"),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="comments",
            name="reply",
        ),
        migrations.AddField(
            model_name="comments",
            name="reply",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="multimedia.comments",
            ),
        ),
    ]
