# Generated by Django 3.1.1 on 2020-09-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("multimedia", "0008_auto_20200927_1701"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="reply",
        ),
        migrations.AddField(
            model_name="comments",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="multimedia.comments",
            ),
        ),
    ]
