# Generated by Django 3.1.1 on 2020-09-29 21:01

from django.conf import settings
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("multimedia", "0010_savedmedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="media",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="media", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="media", to="multimedia.Tags"
            ),
        ),
    ]
