# Generated by Django 3.1.1 on 2020-09-30 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("multimedia", "0011_auto_20200929_2101"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="media", to="multimedia.Tags"
            ),
        ),
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="Views",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="media",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="media", to="multimedia.Views"
            ),
        ),
    ]
